# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_lite.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NCMget_main(object):
    def setupUi(self, NCMget_main):
        NCMget_main.setObjectName("NCMget_main")
        NCMget_main.resize(1024, 768)
        NCMget_main.setMinimumSize(QtCore.QSize(1024, 768))
        NCMget_main.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(NCMget_main)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(20, 90, 351, 31))
        self.SearchButton.setDefault(True)
        self.SearchButton.setFlat(False)
        self.SearchButton.setObjectName("SearchButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.label.setObjectName("label")
        self.SearchName = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchName.setGeometry(QtCore.QRect(20, 50, 351, 31))
        self.SearchName.setObjectName("SearchName")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 351, 491))
        self.groupBox.setObjectName("groupBox")
        self.SearchResultList = QtWidgets.QListWidget(self.groupBox)
        self.SearchResultList.setGeometry(QtCore.QRect(10, 20, 331, 461))
        font = QtGui.QFont()
        font.setFamily("Sarasa UI SC")
        font.setPointSize(10)
        self.SearchResultList.setFont(font)
        self.SearchResultList.setObjectName("SearchResultList")
        self.DownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadButton.setGeometry(QtCore.QRect(450, 570, 201, 51))
        self.DownloadButton.setObjectName("DownloadButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 10, 101, 16))
        self.label_4.setObjectName("label_4")
        self.MediaInfoDisplay = QtWidgets.QLabel(self.centralwidget)
        self.MediaInfoDisplay.setGeometry(QtCore.QRect(450, 50, 511, 31))
        self.MediaInfoDisplay.setStyleSheet("border-style:solid;\n"
"border-left-width:15px;\n"
"border-left-color:blue;\n"
"background-color:#ddffff")
        self.MediaInfoDisplay.setObjectName("MediaInfoDisplay")
        self.PlayButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlayButton.setGeometry(QtCore.QRect(450, 450, 201, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PlayButton.setFont(font)
        self.PlayButton.setObjectName("PlayButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(680, 430, 281, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.AlbumArtImg = QtWidgets.QLabel(self.groupBox_2)
        self.AlbumArtImg.setGeometry(QtCore.QRect(20, 20, 241, 241))
        self.AlbumArtImg.setStyleSheet("border:1px solid black")
        self.AlbumArtImg.setText("")
        self.AlbumArtImg.setObjectName("AlbumArtImg")
        self.SaveSearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveSearchButton.setGeometry(QtCore.QRect(30, 640, 141, 51))
        self.SaveSearchButton.setObjectName("SaveSearchButton")
        self.ResultSaveStatus = QtWidgets.QLabel(self.centralwidget)
        self.ResultSaveStatus.setGeometry(QtCore.QRect(30, 710, 311, 41))
        self.ResultSaveStatus.setText("")
        self.ResultSaveStatus.setObjectName("ResultSaveStatus")
        self.MusicSaveStatus = QtWidgets.QLabel(self.centralwidget)
        self.MusicSaveStatus.setGeometry(QtCore.QRect(450, 630, 201, 51))
        self.MusicSaveStatus.setStyleSheet("border:1px solid red")
        self.MusicSaveStatus.setText("")
        self.MusicSaveStatus.setObjectName("MusicSaveStatus")
        self.LyricShow = QtWidgets.QTextEdit(self.centralwidget)
        self.LyricShow.setGeometry(QtCore.QRect(450, 110, 511, 311))
        font = QtGui.QFont()
        font.setFamily("Sarasa UI SC")
        font.setPointSize(12)
        self.LyricShow.setFont(font)
        self.LyricShow.setReadOnly(True)
        self.LyricShow.setObjectName("LyricShow")
        self.LoadSearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadSearchButton.setGeometry(QtCore.QRect(200, 640, 141, 51))
        self.LoadSearchButton.setObjectName("LoadSearchButton")
        NCMget_main.setCentralWidget(self.centralwidget)

        self.retranslateUi(NCMget_main)
        QtCore.QMetaObject.connectSlotsByName(NCMget_main)

    def retranslateUi(self, NCMget_main):
        _translate = QtCore.QCoreApplication.translate
        NCMget_main.setWindowTitle(_translate("NCMget_main", "NCMget"))
        self.SearchButton.setText(_translate("NCMget_main", "search!"))
        self.label.setText(_translate("NCMget_main", "Song name:"))
        self.groupBox.setTitle(_translate("NCMget_main", "Results:"))
        self.DownloadButton.setText(_translate("NCMget_main", "Download!"))
        self.label_3.setText(_translate("NCMget_main", "Search:"))
        self.label_4.setText(_translate("NCMget_main", "Player:"))
        self.MediaInfoDisplay.setText(_translate("NCMget_main", "Title_info"))
        self.PlayButton.setText(_translate("NCMget_main", "Play"))
        self.groupBox_2.setTitle(_translate("NCMget_main", "AlbumArt:"))
        self.SaveSearchButton.setText(_translate("NCMget_main", "save search"))
        self.LoadSearchButton.setText(_translate("NCMget_main", "load search"))
